[tool.poetry]
name = "weather-app"
version = "0.1.0"
description = ""
authors = ["XERO47 <141753439+XERO47@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
uagents = "^0.6.2"
streamlit = "^1.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
